config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  resources :games, except: :index do
    resources :critics, except: %i[index show]
    resources :involved_companies, only: %i[new create destroy]
    resources :genres, only: :index
    post 'add_genre', on: :member
    delete 'remove_genre', on: :member
    resources :platforms, only: :index
    post 'add_platform', on: :member
    delete 'remove_platform', on: :member
  end
  resources :companies, only: %i[new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies
  has_many :critics, as: :criticable, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/critic.rb
class Critic < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :criticable, polymorphic: true

  validates :title, :body, presence: true
  validates :title, length: { maximum: 40 }
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :cover
  enum category: { main_game: 0, expansion: 1 }
  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies
  has_many :critics, as: :criticable, dependent: :destroy
  has_many :expansions, class_name: 'Game', foreign_key: 'parent_id',
                        dependent: :nullify, inverse_of: false
  belongs_to :parent, class_name: 'Game', optional: true
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true
  validates :rating, inclusion: { in: 0..100, message: 'Should be between 0 and 100' },
                     allow_nil: true
  validate :parent_validation

  def parent_validation
    if expansion?
      errors.add(:parent_id, 'Should be a valid Game id') unless Game.exists?(parent_id)
    elsif main_game?
      errors.add(:parent_id, 'Should be null if main_game') unless parent_id.nil?
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games

  validates :name, presence: true, uniqueness: true
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  belongs_to :company
  belongs_to :game

  validates :developer, :publisher, inclusion: { in: [false, true] }
  validates :company_id, uniqueness: { scope: :game_id }
end

app/models/platform.rb
class Platform < ApplicationRecord
  enum category: {
    console: 0, arcade: 1, platform: 2, operating_system: 3, portable_console: 4, computer: 5
  }
  has_and_belongs_to_many :games

  validates :name, :category, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { visitor: 'visitor', member: 'member', admin: 'admin' }
  has_many :critics, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  validates :username, :email, presence: true, uniqueness: true
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2; end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies/new
  def new
    @company = Company.new
  end

  # POST /companies
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country)
  end
end

app/controllers/critics_controller.rb
class CriticsController < ApplicationController
  # GET /games/:game_id/critics/new
  def new
    @game = Game.find(params[:game_id])
    @critic = @game.critics.new
  end

  # POST /games/:game_id/critics
  def create
    @game = Game.find(params[:game_id])
    @critic = @game.critics.new(critic_params)
    if @critic.save
      redirect_to @game
    else
      render 'new'
    end
  end

  # GET /games/:game_id/critics/:id/edit
  def edit
    @game = Game.find(params[:game_id])
    @critic = @game.critics.find(params[:id])
  end

  # PATCH /games/:game_id/critics/:id
  def update
    @game = Game.find(params[:game_id])
    @critic = @game.critics.find(params[:id])
    if @critic.update(critic_params)
      redirect_to @game
    else
      render 'edit'
    end
  end

  # DELETE /games/:game_id/critics/:id
  def destroy
    @game = Game.find(params[:game_id])
    @critic = @game.critics.find(params[:id])
    @critic.destroy
    redirect_to @game
  end

  private

  def critic_params
    params.require(:critic).permit(:title, :body, :user_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /
  def index; end

  # GET /games/:id
  def show; end

  # GET /games/new
  def new; end

  # POST /games
  def create; end

  # GET /games/:id/edit
  def edit; end

  # PATCH /games/:id
  def update; end

  # DELETE /games/:id
  def destroy; end

  # POST /games/:id/add_genre
  def add_genre
    game = Game.find(params[:id])
    genre = Genre.find(params[:genre_id])
    game.genres << genre
  end

  # DELETE /games/:id/remove_genre
  def remove_genre
    game = Game.find(params[:id])
    genre = Genre.find(params[:genre_id])
    game.genres.delete(genre)
  end

  # POST /games/:id/add_platform
  def add_platform
    game = Game.find(params[:id])
    platform = Platform.find(params[:platform_id])
    game.platforms << platform
  end

  # DELETE /games/:id/remove_platform
  def remove_platform
    game = Game.find(params[:id])
    platform = Platform.find(params[:platform_id])
    game.platforms.delete(platform)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  # GET /games/:game_id/genres
  def index; end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  # GET /games/:game_id/platforms
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/critics_helper.rb
module CriticsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/new.html.erb
<h1>New Company</h1>
<%= form_with model: @company, local: true do |form| %>
  <% if @company.errors.any? %>
    <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>
  <div>
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>
  <%= form.submit 'Create Company' %>
<% end %>
<%= link_to 'Cancel', root_path %>

app/views/critics/_form.html.erb
<%= form_with model: [@game, @critic], local: true do |form| %>
  <% if @critic.errors.any? %>
    <ul>
      <% @critic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.submit 'Submit Critic' %>
<% end %>
<%= link_to 'Cancel', game_path(@game) %> 

app/views/critics/edit.html.erb
<h1>Edit Critic for <%= @game.name %></h1>
<%= render 'form' %>

app/views/critics/new.html.erb
<h1>New Critic for <%= @game.name %></h1>
<%= render 'form' %>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

app/views/games/index.html.erb
<h1>Games</h1>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/genres/new.html.erb
<h1>Genres#new</h1>
<p>Find me in app/views/genres/new.html.erb</p>